module.exports = {
  "skills" : [ {
    "requiredLevel" : 1,
    "orderIndex" : 0,
    "tooltipParams" : "skill/demon-hunter/hungering-arrow",
    "categoryName" : "Primary",
    "categorySlug" : "primary",
    "icon" : "demonhunter_hungeringarrow",
    "name" : "Hungering Arrow",
    "slug" : "hungering-arrow",
    "runes" : [ {
      "requiredLevel" : 6,
      "name" : "Puncturing Arrow",
      "tooltipParams" : "rune/hungering-arrow/d",
      "type" : "d",
      "description" : "<p>Increase the chance for the arrow to pierce to <span class=\"d3-color-green\">50%</span>.</p>",
      "simpleDescription" : "<p>Increase the pierce chance.</p>"
    }, {
      "requiredLevel" : 17,
      "name" : "Serrated Arrow",
      "tooltipParams" : "rune/hungering-arrow/a",
      "type" : "a",
      "description" : "<p>Increase Hatred generated to <span class=\"d3-color-green\">6</span>.</p><p>Hungering Arrow&#39;s damage turns into Fire.</p>",
      "simpleDescription" : "<p>Increase Hatred generated by Hungering Arrow.</p>"
    }, {
      "requiredLevel" : 26,
      "name" : "Shatter Shot",
      "tooltipParams" : "rune/hungering-arrow/b",
      "type" : "b",
      "description" : "<p>If the arrow successfully pierces the first enemy, the arrow splits into <span class=\"d3-color-green\">3</span> arrows.</p><p>Hungering Arrow&#39;s damage turns into Lightning.</p>",
      "simpleDescription" : "<p>The initial attack has a chance to split into multiple arrows.</p>"
    }, {
      "requiredLevel" : 42,
      "name" : "Devouring Arrow",
      "tooltipParams" : "rune/hungering-arrow/c",
      "type" : "c",
      "description" : "<p>Each consecutive pierce increases the damage of the arrow by <span class=\"d3-color-green\">70%</span>.</p><p>Hungering Arrow&#39;s damage turns into Cold.</p>",
      "simpleDescription" : "<p>Increase the damage of the arrow with each enemy pierced.</p>"
    }, {
      "requiredLevel" : 52,
      "name" : "Spray of Teeth",
      "tooltipParams" : "rune/hungering-arrow/e",
      "type" : "e",
      "description" : "<p>Critical Hits cause a burst of bone to explode from the enemy, dealing <span class=\"d3-color-green\">60%</span> weapon damage to enemies within <span class=\"d3-color-green\">10</span> yards.</p>",
      "simpleDescription" : "<p>Critical Hits cause the enemy&#39;s bones to explode.</p>"
    } ],
    "primary" : true,
    "description" : "<p><span class=\"d3-color-gold\">Generate:</span> <span class=\"d3-color-green\">3</span> Hatred</p><p>Fire a magically imbued arrow that seeks out enemies for <span class=\"d3-color-green\">155%</span> weapon damage and has a <span class=\"d3-color-green\">35%</span> chance to pierce through them.</p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Generate:</span> <span class=\"d3-color-green\">3</span> Hatred</p><p>Fire a piercing arrow that seeks additional enemies.</p>"
  }, {
    "requiredLevel" : 2,
    "orderIndex" : 1,
    "tooltipParams" : "skill/demon-hunter/impale",
    "categoryName" : "Secondary",
    "categorySlug" : "secondary",
    "icon" : "demonhunter_impale",
    "name" : "Impale",
    "slug" : "impale",
    "runes" : [ {
      "requiredLevel" : 7,
      "name" : "Impact",
      "tooltipParams" : "rune/impale/b",
      "type" : "b",
      "description" : "<p>The impact causes Knockback and has a <span class=\"d3-color-green\">100%</span> chance to Stun for <span class=\"d3-color-green\">1.5</span> seconds.</p>",
      "simpleDescription" : "<p>The impact causes Knockback and can Stun the enemy.</p>"
    }, {
      "requiredLevel" : 15,
      "name" : "Chemical Burn",
      "tooltipParams" : "rune/impale/c",
      "type" : "c",
      "description" : "<p>The enemy also burns for <span class=\"d3-color-green\">500%</span> weapon damage as Fire over <span class=\"d3-color-green\">2</span> seconds.</p>",
      "simpleDescription" : "<p>Impale causes the enemy to also burn after each strike.</p>"
    }, {
      "requiredLevel" : 28,
      "name" : "Overpenetration",
      "tooltipParams" : "rune/impale/a",
      "type" : "a",
      "description" : "<p>The knife <span class=\"d3-color-green\">pierces</span> through all enemies in a straight line for Cold damage.</p>",
      "simpleDescription" : "<p>The knife <span class=\"d3-color-green\">pierces</span> through all enemies in a straight line.</p>"
    }, {
      "requiredLevel" : 53,
      "name" : "Ricochet",
      "tooltipParams" : "rune/impale/d",
      "type" : "d",
      "description" : "<p>The knife ricochets to <span class=\"d3-color-green\">2</span> additional nearby enemies within <span class=\"d3-color-green\">20</span> yards of each other.</p><p>Impale&#39;s damage turns into Lightning.</p>",
      "simpleDescription" : "<p>The knife ricochets to additional nearby enemies.</p>"
    }, {
      "requiredLevel" : 58,
      "name" : "Grievous Wounds",
      "tooltipParams" : "rune/impale/e",
      "type" : "e",
      "description" : "<p>Critical Hits deal <span class=\"d3-color-green\">330%</span> additional damage.</p>",
      "simpleDescription" : "<p>Critical Hits deal additional damage.</p>"
    } ],
    "primary" : true,
    "description" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">20</span> Hatred</p><p>Throw a knife that impales an enemy for <span class=\"d3-color-green\">750%</span> weapon damage.</p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">20</span> Hatred</p><p>Throw a knife that impales enemies.</p>"
  }, {
    "requiredLevel" : 3,
    "orderIndex" : 2,
    "tooltipParams" : "skill/demon-hunter/entangling-shot",
    "categoryName" : "Primary",
    "categorySlug" : "primary",
    "icon" : "x1_demonhunter_entanglingshot",
    "name" : "Entangling Shot",
    "slug" : "entangling-shot",
    "runes" : [ {
      "requiredLevel" : 9,
      "name" : "Chain Gang",
      "tooltipParams" : "rune/entangling-shot/b",
      "type" : "b",
      "description" : "<p>Entangle and Slow up to <span class=\"d3-color-green\">4</span> enemies with each shot.</p>",
      "simpleDescription" : "<p>Entangle and Slow up to <span class=\"d3-color-green\">4</span> enemies.</p>"
    }, {
      "requiredLevel" : 18,
      "name" : "Shock Collar",
      "tooltipParams" : "rune/entangling-shot/c",
      "type" : "c",
      "description" : "<p>Entangled enemies take <span class=\"d3-color-green\">80%</span> weapon damage as Lightning over <span class=\"d3-color-green\">2</span> seconds.</p>",
      "simpleDescription" : "<p>Entangled enemies take damage from electrified chains.</p>"
    }, {
      "requiredLevel" : 34,
      "name" : "Heavy Burden",
      "tooltipParams" : "rune/entangling-shot/a",
      "type" : "a",
      "description" : "<p>Increase the Slow duration to <span class=\"d3-color-green\">4</span> seconds.</p><p>Entangling Shot&#39;s damage turns into Cold.</p>",
      "simpleDescription" : "<p>Increase the Slow duration.</p>"
    }, {
      "requiredLevel" : 47,
      "name" : "Justice is Served",
      "tooltipParams" : "rune/entangling-shot/d",
      "type" : "d",
      "description" : "<p>Increase Hatred generated to <span class=\"d3-color-green\">6</span>.</p><p>Entangling Shot&#39;s damage turns into Fire.</p>",
      "simpleDescription" : "<p>Increase Hatred generated by Entangling Shot.</p>"
    }, {
      "requiredLevel" : 54,
      "name" : "Bounty Hunter",
      "tooltipParams" : "rune/entangling-shot/e",
      "type" : "e",
      "description" : "<p>Increase the Slow amount to <span class=\"d3-color-green\">80%</span>.</p>",
      "simpleDescription" : "<p>Increase the Slow amount.</p>"
    } ],
    "primary" : true,
    "description" : "<p><span class=\"d3-color-gold\">Generate:</span> <span class=\"d3-color-green\">3</span> Hatred</p><p>Imbue an arrow with shadow energy that deals <span class=\"d3-color-green\">200%</span> weapon damage to the primary enemy and entangles up to <span class=\"d3-color-green\">2</span> enemies, slowing their movement by <span class=\"d3-color-green\">60%</span> for <span class=\"d3-color-green\">2</span> seconds.</p><p>When Entangling Shot hits an enemy, the Slow effect on all entangled enemies is refreshed.</p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Generate:</span> <span class=\"d3-color-green\">3</span> Hatred</p><p>Imbue an arrow with shadow energy, slowing up to <span class=\"d3-color-green\">2</span> enemies.</p>"
  }, {
    "requiredLevel" : 4,
    "orderIndex" : 3,
    "tooltipParams" : "skill/demon-hunter/caltrops",
    "categoryName" : "Defensive",
    "categorySlug" : "defensive",
    "icon" : "demonhunter_caltrops",
    "name" : "Caltrops",
    "slug" : "caltrops",
    "runes" : [ {
      "requiredLevel" : 12,
      "name" : "Hooked Spines",
      "tooltipParams" : "rune/caltrops/b",
      "type" : "b",
      "description" : "<p>Increase the slowing amount to <span class=\"d3-color-green\">80%</span>.</p>",
      "simpleDescription" : "<p>Increase the slowing effect of Caltrops.</p>"
    }, {
      "requiredLevel" : 18,
      "name" : "Torturous Ground",
      "tooltipParams" : "rune/caltrops/c",
      "type" : "c",
      "description" : "<p>When the trap is sprung, all enemies in the area are immobilized for <span class=\"d3-color-green\">2</span> seconds.</p>",
      "simpleDescription" : "<p>Caltrops immobilize enemies caught in the trap.</p>"
    }, {
      "requiredLevel" : 28,
      "name" : "Jagged Spikes",
      "tooltipParams" : "rune/caltrops/a",
      "type" : "a",
      "description" : "<p>Enemies in the area also take <span class=\"d3-color-green\">270%</span> weapon damage as Physical over <span class=\"d3-color-green\">6</span> seconds.</p>",
      "simpleDescription" : "<p>Caltrops can damage enemies.</p>"
    }, {
      "requiredLevel" : 41,
      "name" : "Carved Stakes",
      "tooltipParams" : "rune/caltrops/d",
      "type" : "d",
      "description" : "<p>Reduce the cost of Caltrops to <span class=\"d3-color-green\">3</span> Discipline.</p>",
      "simpleDescription" : "<p>Reduce the Discipline cost of Caltrops.</p>"
    }, {
      "requiredLevel" : 54,
      "name" : "Bait the Trap",
      "tooltipParams" : "rune/caltrops/e",
      "type" : "e",
      "description" : "<p>Become empowered while standing in the area of effect, gaining an additional <span class=\"d3-color-green\">10%</span> Critical Hit Chance.</p>",
      "simpleDescription" : "<p>Gain Critical Hit Chance while standing in the trap.</p>"
    } ],
    "primary" : false,
    "description" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">6</span> Discipline</p><p>Lay a trap of caltrops on the ground that activates when an enemy approaches. Once sprung, the caltrops Slow the movement of enemies within <span class=\"d3-color-green\">12</span> yards by <span class=\"d3-color-green\">60%</span>. This trap lasts <span class=\"d3-color-green\">6</span> seconds.</p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">6</span> Discipline</p><p>Place a trap that slows enemies.</p>"
  }, {
    "requiredLevel" : 5,
    "orderIndex" : 4,
    "tooltipParams" : "skill/demon-hunter/rapid-fire",
    "categoryName" : "Secondary",
    "categorySlug" : "secondary",
    "icon" : "demonhunter_rapidfire",
    "name" : "Rapid Fire",
    "slug" : "rapid-fire",
    "runes" : [ {
      "requiredLevel" : 11,
      "name" : "Withering Fire",
      "tooltipParams" : "rune/rapid-fire/d",
      "type" : "d",
      "description" : "<p>Reduce the initial Hatred cost to <span class=\"d3-color-green\">10</span> and ignite your arrows, causing them to deal Fire damage.</p>",
      "simpleDescription" : "<p>Shoot fire arrows and reduce the Hatred cost of Rapid Fire.</p>"
    }, {
      "requiredLevel" : 19,
      "name" : "Frost Shots",
      "tooltipParams" : "rune/rapid-fire/e",
      "type" : "e",
      "description" : "<p>Enemies hit by Rapid Fire are <span class=\"d3-color-green\">Chilled</span> by <span class=\"d3-color-green\">80%</span> for <span class=\"d3-color-green\">2</span> seconds.</p><p>Rapid Fire&#39;s damage turns into Cold.</p>",
      "simpleDescription" : "<p>Enemies hit by Rapid Fire are Chilled.</p>"
    }, {
      "requiredLevel" : 32,
      "name" : "Fire Support",
      "tooltipParams" : "rune/rapid-fire/c",
      "type" : "c",
      "description" : "<p>While channeling Rapid Fire, launch <span class=\"d3-color-green\">2</span> homing rockets every second. Each rocket deals <span class=\"d3-color-green\">145%</span> weapon damage as Physical to nearby enemies.</p>",
      "simpleDescription" : "<p>Launch homing rockets while using Rapid Fire.</p>"
    }, {
      "requiredLevel" : 45,
      "name" : "High Velocity",
      "tooltipParams" : "rune/rapid-fire/b",
      "type" : "b",
      "description" : "<p>Fire lightning arrows that have a <span class=\"d3-color-green\">50%</span> chance to pierce through enemies.</p>",
      "simpleDescription" : "<p>Fire lightning arrows that have a chance to pierce through enemies.</p>"
    }, {
      "requiredLevel" : 56,
      "name" : "Bombardment",
      "tooltipParams" : "rune/rapid-fire/a",
      "type" : "a",
      "description" : "<p>Rapidly fire grenades that explode for <span class=\"d3-color-green\">545%</span> weapon damage as Fire to all enemies within a <span class=\"d3-color-green\">8</span> yard radius.</p>",
      "simpleDescription" : "<p>Rapidly fire grenades that explode.</p>"
    } ],
    "primary" : true,
    "description" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">20</span> Hatred initially, and an additional <span class=\"d3-color-green\">6</span> Hatred while channeling</p><p>Rapidly fire for <span class=\"d3-color-green\">685%</span> weapon damage as Physical.</p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">20</span> Hatred initially, and an additional <span class=\"d3-color-green\">6</span> Hatred while channeling</p><p>Hold your ground and continually fire a stream of arrows.</p>"
  }, {
    "requiredLevel" : 8,
    "orderIndex" : 5,
    "tooltipParams" : "skill/demon-hunter/smoke-screen",
    "categoryName" : "Defensive",
    "categorySlug" : "defensive",
    "icon" : "demonhunter_smokescreen",
    "name" : "Smoke Screen",
    "slug" : "smoke-screen",
    "runes" : [ {
      "requiredLevel" : 14,
      "name" : "Displacement",
      "tooltipParams" : "rune/smoke-screen/e",
      "type" : "e",
      "description" : "<p>Gain <span class=\"d3-color-green\">100%</span> movement speed while invisible.</p>",
      "simpleDescription" : "<p>Gain a movement speed bonus while invisible.</p>"
    }, {
      "requiredLevel" : 23,
      "name" : "Lingering Fog",
      "tooltipParams" : "rune/smoke-screen/b",
      "type" : "b",
      "description" : "<p>Increase the duration to <span class=\"d3-color-green\">1.5</span> seconds.</p>",
      "simpleDescription" : "<p>Increase the duration of Smoke Screen.</p>"
    }, {
      "requiredLevel" : 33,
      "name" : "Healing Vapors",
      "tooltipParams" : "rune/smoke-screen/c",
      "type" : "c",
      "description" : "<p>Regenerate <span class=\"d3-color-green\">15%</span> Life while invisible.</p>",
      "simpleDescription" : "<p>Regenerate Life while invisible.</p>"
    }, {
      "requiredLevel" : 44,
      "name" : "Special Recipe",
      "tooltipParams" : "rune/smoke-screen/d",
      "type" : "d",
      "description" : "<p>Reduce the cost to <span class=\"d3-color-green\">10</span> Discipline.</p>",
      "simpleDescription" : "<p>Reduce the Discipline cost.</p>"
    }, {
      "requiredLevel" : 59,
      "name" : "Vanishing Powder",
      "tooltipParams" : "rune/smoke-screen/a",
      "type" : "a",
      "description" : "<p>Remove the Discipline cost but increase the cooldown to <span class=\"d3-color-green\">6</span> seconds.</p>",
      "simpleDescription" : "<p>Remove the Discipline cost but increase the cooldown.</p>"
    } ],
    "primary" : false,
    "description" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">14</span> Discipline<br/><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">1.5</span> seconds</p><p>Vanish behind a wall of smoke, becoming momentarily invisible for <span class=\"d3-color-green\">1</span> seconds.</p><p><span class=\"d3-color-yellow\">This ability does not start its cooldown until after its effects expire.</span></p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">14</span> Discipline<br/><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">1.5</span> seconds</p><p>Vanish from sight for a limited time.</p><p><span class=\"d3-color-yellow\">This ability does not start its cooldown until after its effects expire.</span></p>"
  }, {
    "requiredLevel" : 9,
    "orderIndex" : 6,
    "tooltipParams" : "skill/demon-hunter/vault",
    "categoryName" : "Hunting",
    "categorySlug" : "hunting",
    "icon" : "demonhunter_vault",
    "name" : "Vault",
    "slug" : "vault",
    "runes" : [ {
      "requiredLevel" : 16,
      "name" : "Action Shot",
      "tooltipParams" : "rune/vault/c",
      "type" : "c",
      "description" : "<p>While Vaulting, shoot <span class=\"d3-color-green\">4</span> arrows for <span class=\"d3-color-green\">75%</span> weapon damage at nearby enemies. These shots are guaranteed Critical Hits.</p>",
      "simpleDescription" : "<p>Fire at nearby enemies while Vaulting.</p>"
    }, {
      "requiredLevel" : 23,
      "name" : "Rattling Roll",
      "tooltipParams" : "rune/vault/e",
      "type" : "e",
      "description" : "<p>Enemies you vault through are knocked away and Stunned for <span class=\"d3-color-green\">1.5</span> seconds.</p>",
      "simpleDescription" : "<p>Stun and Knockback enemies you vault through.</p>"
    }, {
      "requiredLevel" : 33,
      "name" : "Tumble",
      "tooltipParams" : "rune/vault/d",
      "type" : "d",
      "description" : "<p>After using Vault, your next Vault within <span class=\"d3-color-green\">6</span> seconds has its Discipline cost reduced by <span class=\"d3-color-green\">50%</span>.</p>",
      "simpleDescription" : "<p>Reduce the Discipline cost if you Vault immediately again after landing.</p>"
    }, {
      "requiredLevel" : 38,
      "name" : "Acrobatics",
      "tooltipParams" : "rune/vault/b",
      "type" : "b",
      "description" : "<p>Remove the Discipline cost but add an <span class=\"d3-color-green\">6</span> second cooldown.</p>",
      "simpleDescription" : "<p>Remove the Discipline cost but add a cooldown.</p>"
    }, {
      "requiredLevel" : 49,
      "name" : "Trail of Cinders",
      "tooltipParams" : "rune/vault/a",
      "type" : "a",
      "description" : "<p>Leave a trail of fire in your wake that deals <span class=\"d3-color-green\">300%</span> weapon damage as Fire over <span class=\"d3-color-green\">3</span> seconds.</p>",
      "simpleDescription" : "<p>Leave a trail of fire in your wake.</p>"
    } ],
    "primary" : true,
    "description" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">8</span> Discipline</p><p>Tumble acrobatically <span class=\"d3-color-green\">35</span> yards.</p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">8</span> Discipline</p><p>Tumble acrobatically to avoid attacks.</p>"
  }, {
    "requiredLevel" : 11,
    "orderIndex" : 7,
    "tooltipParams" : "skill/demon-hunter/bolas",
    "categoryName" : "Primary",
    "categorySlug" : "primary",
    "icon" : "demonhunter_bolas",
    "name" : "Bolas",
    "slug" : "bolas",
    "runes" : [ {
      "requiredLevel" : 14,
      "name" : "Volatile Explosives",
      "tooltipParams" : "rune/bolas/a",
      "type" : "a",
      "description" : "<p>Increase the explosion radius to <span class=\"d3-color-green\">20</span> yards.</p>",
      "simpleDescription" : "<p>Increase the explosion radius of Bola.</p>"
    }, {
      "requiredLevel" : 24,
      "name" : "Thunder Ball",
      "tooltipParams" : "rune/bolas/c",
      "type" : "c",
      "description" : "<p>Increase Hatred generated to <span class=\"d3-color-green\">6</span>.</p>",
      "simpleDescription" : "<p>Increase Hatred generated by Bolas.</p>"
    }, {
      "requiredLevel" : 37,
      "name" : "Freezing Strike",
      "tooltipParams" : "rune/bolas/b",
      "type" : "b",
      "description" : "<p>Shoot <span class=\"d3-color-green\">3</span> bolas that each deal <span class=\"d3-color-green\">160%</span> weapon damage as Cold. The bolas no longer explode for area damage to nearby enemies.</p><p>Enemies hit have a <span class=\"d3-color-green\">50%</span> chance to be <span class=\"d3-color-green\">Frozen</span> for <span class=\"d3-color-green\">1</span> seconds.</p>",
      "simpleDescription" : "<p>Fire multiple shots of Cold that Freeze and no longer explode.</p>"
    }, {
      "requiredLevel" : 51,
      "name" : "Bitter Pill",
      "tooltipParams" : "rune/bolas/d",
      "type" : "d",
      "description" : "<p>When the bola explodes, you have a <span class=\"d3-color-green\">15%</span> chance to gain <span class=\"d3-color-green\">2</span> Discipline.</p><p>Bolas&#39;s damage turns into Lightning.</p>",
      "simpleDescription" : "<p>When the bola explodes, you have a chance to gain Discipline.</p>"
    }, {
      "requiredLevel" : 57,
      "name" : "Imminent Doom",
      "tooltipParams" : "rune/bolas/e",
      "type" : "e",
      "description" : "<p>Augment the bola to deal <span class=\"d3-color-green\">216%</span> weapon damage as Fire to the enemy and <span class=\"d3-color-green\">149%</span> weapon damage as Fire to all other enemies within <span class=\"d3-color-green\">14</span> yards, but increases the explosion delay to <span class=\"d3-color-green\">2</span> seconds.</p>",
      "simpleDescription" : "<p>Fire a bola that deals increased damage, but takes longer to explode.</p>"
    } ],
    "primary" : true,
    "description" : "<p><span class=\"d3-color-gold\">Generate:</span> <span class=\"d3-color-green\">3</span> Hatred</p><p>Shoot out an explosive bola that wraps itself around the enemy. After <span class=\"d3-color-green\">1</span> seconds, the bola explodes dealing <span class=\"d3-color-green\">160%</span> weapon damage as Fire to the enemy and an additional <span class=\"d3-color-green\">110%</span> weapon damage as Fire to all other enemies within <span class=\"d3-color-green\">14</span> yards.</p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Generate:</span> <span class=\"d3-color-green\">3</span> Hatred</p><p>Fire a bola that wraps around an enemy and explodes.</p>"
  }, {
    "requiredLevel" : 12,
    "orderIndex" : 8,
    "tooltipParams" : "skill/demon-hunter/chakram",
    "categoryName" : "Secondary",
    "categorySlug" : "secondary",
    "icon" : "demonhunter_chakram",
    "name" : "Chakram",
    "slug" : "chakram",
    "runes" : [ {
      "requiredLevel" : 18,
      "name" : "Twin Chakrams",
      "tooltipParams" : "rune/chakram/a",
      "type" : "a",
      "description" : "<p>A second Chakram mirrors the first. Each Chakram deals <span class=\"d3-color-green\">220%</span> weapon damage as Fire.</p>",
      "simpleDescription" : "<p>Throw two Chakrams instead of one.</p>"
    }, {
      "requiredLevel" : 26,
      "name" : "Serpentine",
      "tooltipParams" : "rune/chakram/c",
      "type" : "c",
      "description" : "<p>The Chakram follows a slow curve, dealing <span class=\"d3-color-green\">500%</span> weapon damage as Cold to enemies along the path.</p>",
      "simpleDescription" : "<p>The Chakram follows a slow curve, hitting enemies in its path.</p>"
    }, {
      "requiredLevel" : 34,
      "name" : "Razor Disk",
      "tooltipParams" : "rune/chakram/d",
      "type" : "d",
      "description" : "<p>The Chakram spirals out from the targeted location dealing <span class=\"d3-color-green\">380%</span> weapon damage as Physical to enemies along the path.</p>",
      "simpleDescription" : "<p>The Chakram spirals out from the targeted location.</p>"
    }, {
      "requiredLevel" : 48,
      "name" : "Boomerang",
      "tooltipParams" : "rune/chakram/b",
      "type" : "b",
      "description" : "<p>The Chakram path turns into a loop, dealing <span class=\"d3-color-green\">400%</span> weapon damage as Lightning to enemies along its path.</p>",
      "simpleDescription" : "<p>Throw an electrified Chakram that returns to you.</p>"
    }, {
      "requiredLevel" : 57,
      "name" : "Shuriken Cloud",
      "tooltipParams" : "rune/chakram/e",
      "type" : "e",
      "description" : "<p>Surround yourself with a cloud of spinning Chakrams, dealing <span class=\"d3-color-green\">200%</span> weapon damage per second as Physical to nearby enemies. Lasts <span class=\"d3-color-green\">120</span> seconds.</p>",
      "simpleDescription" : "<p>Surround yourself with spinning Chakrams.</p>"
    } ],
    "primary" : true,
    "description" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">10</span> Hatred</p><p>Fire a swirling Chakram that deals <span class=\"d3-color-green\">380%</span> weapon damage as Physical to enemies along its path.</p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">10</span> Hatred</p><p>Release a spinning blade of death that slices through enemies.</p>"
  }, {
    "requiredLevel" : 13,
    "orderIndex" : 9,
    "tooltipParams" : "skill/demon-hunter/preparation",
    "categoryName" : "Hunting",
    "categorySlug" : "hunting",
    "icon" : "demonhunter_preparation",
    "name" : "Preparation",
    "slug" : "preparation",
    "runes" : [ {
      "requiredLevel" : 19,
      "name" : "Invigoration",
      "tooltipParams" : "rune/preparation/b",
      "type" : "b",
      "description" : "<p><span class=\"d3-color-gold\">Passive:</span> Permanently increase maximum Discipline by <span class=\"d3-color-green\">15</span>.</p>",
      "simpleDescription" : "<p><span class=\"d3-color-gold\">Passive:</span> Permanently increase maximum Discipline.</p>"
    }, {
      "requiredLevel" : 25,
      "name" : "Punishment",
      "tooltipParams" : "rune/preparation/a",
      "type" : "a",
      "description" : "<p>Restore <span class=\"d3-color-green\">75</span> Hatred.</p><p>Preparation has a <span class=\"d3-color-green\">20</span> second cooldown.</p>",
      "simpleDescription" : "<p>Restores Hatred and has a shorter cooldown.</p>"
    }, {
      "requiredLevel" : 35,
      "name" : "Battle Scars",
      "tooltipParams" : "rune/preparation/d",
      "type" : "d",
      "description" : "<p>Gain <span class=\"d3-color-green\">40%</span> Life when using Preparation.</p>",
      "simpleDescription" : "<p>Gain Life when using Preparation.</p>"
    }, {
      "requiredLevel" : 44,
      "name" : "Focused Mind",
      "tooltipParams" : "rune/preparation/c",
      "type" : "c",
      "description" : "<p>Gain <span class=\"d3-color-green\">45</span> Discipline over <span class=\"d3-color-green\">15</span> seconds instead of restoring it immediately.</p>",
      "simpleDescription" : "<p>Continually gain Discipline over time instead of replenishing Discipline immediately.</p>"
    }, {
      "requiredLevel" : 52,
      "name" : "Backup Plan",
      "tooltipParams" : "rune/preparation/e",
      "type" : "e",
      "description" : "<p>There is a <span class=\"d3-color-green\">30%</span> chance that Preparation&#39;s cooldown will not be triggered.</p>",
      "simpleDescription" : "<p>Grants a chance that the cooldown will not be triggered when using Preparation.</p>"
    } ],
    "primary" : false,
    "description" : "<p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">45</span> seconds</p><p>Instantly restore <span class=\"d3-color-green\">30</span> Discipline.</p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">45</span> seconds</p><p>Focus and instantly restore <span class=\"d3-color-green\">30</span> Discipline.</p>"
  }, {
    "requiredLevel" : 14,
    "orderIndex" : 10,
    "tooltipParams" : "skill/demon-hunter/fan-of-knives",
    "categoryName" : "Devices",
    "categorySlug" : "devices",
    "icon" : "demonhunter_fanofknives",
    "name" : "Fan of Knives",
    "slug" : "fan-of-knives",
    "runes" : [ {
      "requiredLevel" : 23,
      "name" : "Pinpoint Accuracy",
      "tooltipParams" : "rune/fan-of-knives/d",
      "type" : "d",
      "description" : "<p>Increase cooldown to <span class=\"d3-color-green\">15</span> seconds and increase damage to <span class=\"d3-color-green\">1600%</span> weapon damage as Lightning.</p>",
      "simpleDescription" : "<p>Increase the cooldown and damage.</p>"
    }, {
      "requiredLevel" : 32,
      "name" : "Bladed Armor",
      "tooltipParams" : "rune/fan-of-knives/e",
      "type" : "e",
      "description" : "<p>Gain <span class=\"d3-color-green\">40%</span> additional armor for <span class=\"d3-color-green\">6</span> seconds.</p><p>Fan of Knives&#39; damage turns into Cold.</p>",
      "simpleDescription" : "<p>Gain additional armor after using Fan of Knives.</p>"
    }, {
      "requiredLevel" : 38,
      "name" : "Knives Expert",
      "tooltipParams" : "rune/fan-of-knives/a",
      "type" : "a",
      "description" : "<p>Remove the cooldown but add a <span class=\"d3-color-green\">30</span> Hatred cost.</p><p>Fan of Knives&#39; damage turns into Fire.</p>",
      "simpleDescription" : "<p>Remove the cooldown but add a Hatred cost.</p>"
    }, {
      "requiredLevel" : 44,
      "name" : "Fan of Daggers",
      "tooltipParams" : "rune/fan-of-knives/c",
      "type" : "c",
      "description" : "<p>Enemies hit are Stunned for <span class=\"d3-color-green\">3</span> seconds.</p><p>Fan of Knives&#39; damage turns into Fire.</p>",
      "simpleDescription" : "<p>Enemies hit are Stunned.</p>"
    }, {
      "requiredLevel" : 59,
      "name" : "Assassin's Knives",
      "tooltipParams" : "rune/fan-of-knives/b",
      "type" : "b",
      "description" : "<p>Also throw long-range knives that deal <span class=\"d3-color-green\">620%</span> weapon damage to <span class=\"d3-color-green\">5</span> additional enemies.</p>",
      "simpleDescription" : "<p>Also throw long-range knives at random enemies.</p>"
    } ],
    "primary" : false,
    "description" : "<p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">10</span> seconds</p><p>Throw knives out in a spiral around you, dealing <span class=\"d3-color-green\">620%</span> weapon damage to all enemies within <span class=\"d3-color-green\">20</span> yards. Your knives will also Slow the movement of enemies by <span class=\"d3-color-green\">60%</span> for <span class=\"d3-color-green\">1</span> seconds.</p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">10</span> seconds</p><p>Unleash a flurry of knives that strike and Slow all nearby enemies.</p>"
  }, {
    "requiredLevel" : 14,
    "orderIndex" : 11,
    "tooltipParams" : "skill/demon-hunter/evasive-fire",
    "categoryName" : "Primary",
    "categorySlug" : "primary",
    "icon" : "x1_demonhunter_evasivefire",
    "name" : "Evasive Fire",
    "slug" : "evasive-fire",
    "runes" : [ {
      "requiredLevel" : 21,
      "name" : "Hardened",
      "tooltipParams" : "rune/evasive-fire/a",
      "type" : "a",
      "description" : "<p>Instead of backflipping, your Armor is increased by <span class=\"d3-color-green\">25%</span> for <span class=\"d3-color-green\">3</span> seconds.</p>",
      "simpleDescription" : "<p>Increase your Armor temporarily instead of backflipping.</p>"
    }, {
      "requiredLevel" : 26,
      "name" : "Parting Gift",
      "tooltipParams" : "rune/evasive-fire/c",
      "type" : "c",
      "description" : "<p>Whenever a backflip is triggered, leave a bomb behind that explodes for <span class=\"d3-color-green\">150%</span> weapon damage as Physical in a <span class=\"d3-color-green\">12</span> yard radius after <span class=\"d3-color-green\">0.6</span> seconds.</p>",
      "simpleDescription" : "<p>Drop a bomb when you backflip.</p>"
    }, {
      "requiredLevel" : 34,
      "name" : "Covering Fire",
      "tooltipParams" : "rune/evasive-fire/b",
      "type" : "b",
      "description" : "<p>Increase the damage of side bolts to <span class=\"d3-color-green\">200%</span> weapon damage as Fire.</p>",
      "simpleDescription" : "<p>Increase the damage of side bolts.</p>"
    }, {
      "requiredLevel" : 42,
      "name" : "Focus",
      "tooltipParams" : "rune/evasive-fire/e",
      "type" : "e",
      "description" : "<p>Instead of backflipping, increase Hatred generated to <span class=\"d3-color-green\">7</span>.</p><p>Evasive Fire&#39;s damage turns into Cold.</p>",
      "simpleDescription" : "<p>Increase Hatred generated instead of backflipping.</p>"
    }, {
      "requiredLevel" : 53,
      "name" : "Surge",
      "tooltipParams" : "rune/evasive-fire/d",
      "type" : "d",
      "description" : "<p>Increase the backflip distance to <span class=\"d3-color-green\">15</span> yards.</p><p>Evasive Fire&#39;s damage turns into Lightning.</p>",
      "simpleDescription" : "<p>Increase the backflip distance.</p>"
    } ],
    "primary" : true,
    "description" : "<p><span class=\"d3-color-gold\">Generate:</span> <span class=\"d3-color-green\">4</span> Hatred</p><p>Shoot a spread of bolts that hits the primary enemy for <span class=\"d3-color-green\">200%</span> weapon damage and two additional enemies for <span class=\"d3-color-green\">100%</span> weapon damage.</p><p>If an enemy is in front of you at close range, you will backflip away <span class=\"d3-color-green\">5</span> yards.</p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Generate:</span> <span class=\"d3-color-green\">4</span> Hatred</p><p>Fire at three enemies and occasionally perform an evasive backflip if any enemies are close.</p>"
  }, {
    "requiredLevel" : 15,
    "orderIndex" : 12,
    "tooltipParams" : "skill/demon-hunter/grenade",
    "categoryName" : "Primary",
    "categorySlug" : "primary",
    "icon" : "demonhunter_grenades",
    "name" : "Grenade",
    "slug" : "grenade",
    "runes" : [ {
      "requiredLevel" : 22,
      "name" : "Tinkerer",
      "tooltipParams" : "rune/grenade/d",
      "type" : "d",
      "description" : "<p>Increase Hatred generated to <span class=\"d3-color-green\">6</span>.</p>",
      "simpleDescription" : "<p>Increase Hatred generated by Grenade.</p>"
    }, {
      "requiredLevel" : 32,
      "name" : "Cluster Grenades",
      "tooltipParams" : "rune/grenade/b",
      "type" : "b",
      "description" : "<p>Throw cluster grenades that deal <span class=\"d3-color-green\">200%</span> weapon damage as Fire over a <span class=\"d3-color-green\">9</span> yard radius.</p>",
      "simpleDescription" : "<p>Throw cluster grenades with large explosions.</p>"
    }, {
      "requiredLevel" : 40,
      "name" : "Grenade Cache",
      "tooltipParams" : "rune/grenade/c",
      "type" : "c",
      "description" : "<p>Throw out <span class=\"d3-color-green\">3</span> grenades that explode for <span class=\"d3-color-green\">160%</span> weapon damage as Fire each.</p>",
      "simpleDescription" : "<p>Throw <span class=\"d3-color-green\">2</span> additional grenades.</p>"
    }, {
      "requiredLevel" : 48,
      "name" : "Stun Grenade",
      "tooltipParams" : "rune/grenade/e",
      "type" : "e",
      "description" : "<p>Hurl a Lightning grenade that has a <span class=\"d3-color-green\">20%</span> chance to Stun enemies for <span class=\"d3-color-green\">1.5</span> seconds.</p>",
      "simpleDescription" : "<p>The grenade has a chance to Stun enemies.</p>"
    }, {
      "requiredLevel" : 60,
      "name" : "Cold Grenade",
      "tooltipParams" : "rune/grenade/a",
      "type" : "a",
      "description" : "<p>Throw a grenade that explodes for <span class=\"d3-color-green\">160%</span> weapon damage as Cold and leaves a cloud that deals an additional <span class=\"d3-color-green\">120%</span> weapon damage as Cold over <span class=\"d3-color-green\">3</span> seconds to enemies who stand in the area and <span class=\"d3-color-green\">Chills</span> them.</p>",
      "simpleDescription" : "<p>Throw a grenade that explodes and leave a cloud of Cold.</p>"
    } ],
    "primary" : true,
    "description" : "<p><span class=\"d3-color-gold\">Generate:</span> <span class=\"d3-color-green\">3</span> Hatred</p><p>Throw a grenade that bounces and explodes for <span class=\"d3-color-green\">160%</span> weapon damage as Fire.</p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Generate:</span> <span class=\"d3-color-green\">3</span> Hatred</p><p>Throw a grenade that bounces and explodes.</p>"
  }, {
    "requiredLevel" : 16,
    "orderIndex" : 13,
    "tooltipParams" : "skill/demon-hunter/shadow-power",
    "categoryName" : "Defensive",
    "categorySlug" : "defensive",
    "icon" : "demonhunter_shadowpower",
    "name" : "Shadow Power",
    "slug" : "shadow-power",
    "runes" : [ {
      "requiredLevel" : 21,
      "name" : "Night Bane",
      "tooltipParams" : "rune/shadow-power/a",
      "type" : "a",
      "description" : "<p>Slow the movement speed of enemies within <span class=\"d3-color-green\">30</span> yards by <span class=\"d3-color-green\">80%</span> for <span class=\"d3-color-green\">5</span> seconds.</p>",
      "simpleDescription" : "<p>Slow the movement speed of enemies around you.</p>"
    }, {
      "requiredLevel" : 29,
      "name" : "Blood Moon",
      "tooltipParams" : "rune/shadow-power/e",
      "type" : "e",
      "description" : "<p>Increase the Life per Hit gain to <span class=\"d3-color-green\">32185</span>.</p>",
      "simpleDescription" : "<p>Increase the amount of Life gained.</p>"
    }, {
      "requiredLevel" : 37,
      "name" : "Well of Darkness",
      "tooltipParams" : "rune/shadow-power/d",
      "type" : "d",
      "description" : "<p>Reduce the cost to <span class=\"d3-color-green\">10</span> Discipline.</p>",
      "simpleDescription" : "<p>Reduce the Discipline cost.</p>"
    }, {
      "requiredLevel" : 51,
      "name" : "Gloom",
      "tooltipParams" : "rune/shadow-power/c",
      "type" : "c",
      "description" : "<p>Reduce damage taken by <span class=\"d3-color-green\">35%</span> while Shadow Power is active.</p>",
      "simpleDescription" : "<p>Reduce damage taken while Shadow Power is active.</p>"
    }, {
      "requiredLevel" : 58,
      "name" : "Shadow Glide",
      "tooltipParams" : "rune/shadow-power/b",
      "type" : "b",
      "description" : "<p>Gain <span class=\"d3-color-green\">30%</span> increased movement speed while Shadow Power is active.</p>",
      "simpleDescription" : "<p>Gain increased movement speed while Shadow Power is active.</p>"
    } ],
    "primary" : false,
    "description" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">14</span> Discipline</p><p>Draw in the power of the shadows, gaining <span class=\"d3-color-green\">16093</span> Life per Hit for <span class=\"d3-color-green\">5</span> seconds.</p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">14</span> Discipline</p><p>Gain Life for dealing damage for <span class=\"d3-color-green\">5</span> seconds.</p>"
  }, {
    "requiredLevel" : 17,
    "orderIndex" : 14,
    "tooltipParams" : "skill/demon-hunter/spike-trap",
    "categoryName" : "Devices",
    "categorySlug" : "devices",
    "icon" : "demonhunter_spiketrap",
    "name" : "Spike Trap",
    "slug" : "spike-trap",
    "runes" : [ {
      "requiredLevel" : 27,
      "name" : "Echoing Blast",
      "tooltipParams" : "rune/spike-trap/b",
      "type" : "b",
      "description" : "<p>Increase the damage of each explosion to <span class=\"d3-color-green\">420%</span> weapon damage and turns the damage into Cold.</p>",
      "simpleDescription" : "<p>Lay a cold trap that causes powerful blasts.</p>"
    }, {
      "requiredLevel" : 30,
      "name" : "Sticky Trap",
      "tooltipParams" : "rune/spike-trap/c",
      "type" : "c",
      "description" : "<p>Plant a bomb on an enemy rather than on the ground. After <span class=\"d3-color-green\">2</span> seconds, the bomb explodes dealing <span class=\"d3-color-green\">800%</span> weapon damage as Fire to all enemies within <span class=\"d3-color-green\">16</span> yards.</p>",
      "simpleDescription" : "<p>Plant a single bomb on an enemy.</p>"
    }, {
      "requiredLevel" : 39,
      "name" : "Long Fuse",
      "tooltipParams" : "rune/spike-trap/a",
      "type" : "a",
      "description" : "<p>Increase the arming and re-arming time to <span class=\"d3-color-green\">3</span> seconds but increases damage to <span class=\"d3-color-green\">520%</span> weapon damage as Fire.</p>",
      "simpleDescription" : "<p>A more powerful trap with a longer fuse.</p>"
    }, {
      "requiredLevel" : 46,
      "name" : "Lightning Rod",
      "tooltipParams" : "rune/spike-trap/e",
      "type" : "e",
      "description" : "<p>When the trap is triggered, it releases a pulse of lightning that will bounce to up to <span class=\"d3-color-green\">3</span> enemies for <span class=\"d3-color-green\">500%</span> weapon damage as Lightning.</p>",
      "simpleDescription" : "<p>Lay an electrified trap that has a chance to electrocute multiple enemies.</p>"
    }, {
      "requiredLevel" : 55,
      "name" : "Scatter",
      "tooltipParams" : "rune/spike-trap/d",
      "type" : "d",
      "description" : "<p>Simultaneously lay <span class=\"d3-color-green\">3</span> traps.</p>",
      "simpleDescription" : "<p>Simultaneously lay multiple traps.</p>"
    } ],
    "primary" : true,
    "description" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">30</span> Hatred</p><p>Lay a trap that arms after <span class=\"d3-color-green\">2</span> seconds and triggers when an enemy approaches. The trap has a <span class=\"d3-color-green\">2</span> second re-arming time and can explode up to <span class=\"d3-color-green\">3</span> times, each time dealing <span class=\"d3-color-green\">340%</span> weapon damage as Fire to all enemies within <span class=\"d3-color-green\">8</span> yards.</p><p>You can have a maximum of <span class=\"d3-color-green\">3</span> Spike Traps active at one time.</p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">30</span> Hatred</p><p>A deadly trap that explodes on contact once armed.</p>"
  }, {
    "requiredLevel" : 17,
    "orderIndex" : 15,
    "tooltipParams" : "skill/demon-hunter/companion",
    "categoryName" : "Hunting",
    "categorySlug" : "hunting",
    "icon" : "x1_demonhunter_companion",
    "name" : "Companion",
    "slug" : "companion",
    "runes" : [ {
      "requiredLevel" : 22,
      "name" : "Spider Companion",
      "tooltipParams" : "rune/companion/a",
      "type" : "a",
      "description" : "<p><span class=\"d3-color-gold\">Active:</span> Your spider throws webs at all enemies within <span class=\"d3-color-green\">25</span> yards of you and him, Slowing them by <span class=\"d3-color-green\">80%</span> for <span class=\"d3-color-green\">5</span> seconds.</p><p><span class=\"d3-color-gold\">Passive:</span> Summons a spider companion that attacks enemies in front of him for <span class=\"d3-color-green\">100%</span> weapon damage as Physical.</p><p>The spider&#39;s attacks Slow enemies by <span class=\"d3-color-green\">60%</span> for <span class=\"d3-color-green\">3</span> seconds.</p>",
      "simpleDescription" : "<p><span class=\"d3-color-gold\">Active:</span> Your spider throws webs at nearby enemies.</p><p><span class=\"d3-color-gold\">Passive:</span> Summons a spider companion that attacks and Slows enemies.</p>"
    }, {
      "requiredLevel" : 29,
      "name" : "Bat Companion",
      "tooltipParams" : "rune/companion/d",
      "type" : "d",
      "description" : "<p><span class=\"d3-color-gold\">Active:</span> Instantly gain <span class=\"d3-color-green\">50</span> Hatred.</p><p><span class=\"d3-color-gold\">Passive:</span> Summons a bat companion that attacks for <span class=\"d3-color-green\">100%</span> of your weapon damage as Physical.</p><p>The bat grants you <span class=\"d3-color-green\">1</span> Hatred per second.</p>",
      "simpleDescription" : "<p><span class=\"d3-color-gold\">Active:</span> Instantly gain Hatred.</p><p><span class=\"d3-color-gold\">Passive:</span> Summons a bat companion that increases your Hatred regeneration.</p>"
    }, {
      "requiredLevel" : 41,
      "name" : "Boar Companion",
      "tooltipParams" : "rune/companion/b",
      "type" : "b",
      "description" : "<p><span class=\"d3-color-gold\">Active:</span> Your boar charges to you, then taunts all enemies within <span class=\"d3-color-green\">20</span> yards for <span class=\"d3-color-green\">5</span> seconds.</p><p><span class=\"d3-color-gold\">Passive:</span> Summons a boar companion that attacks enemies for <span class=\"d3-color-green\">100%</span> of your weapon damage as Physical.</p><p>The boar increases your Life regeneration by <span class=\"d3-color-green\">5364</span> per second and increases your resistance to all damage types by <span class=\"d3-color-green\">20%</span>.</p>",
      "simpleDescription" : "<p><span class=\"d3-color-gold\">Active:</span> Your boar charges to you and taunts nearby enemies.</p><p><span class=\"d3-color-gold\">Passive:</span> Summons a boar companion that provides Life regeneration and increased resistances.</p>"
    }, {
      "requiredLevel" : 46,
      "name" : "Ferret Companion",
      "tooltipParams" : "rune/companion/e",
      "type" : "e",
      "description" : "<p><span class=\"d3-color-gold\">Active:</span> Instantly pick up all health globes and gold within <span class=\"d3-color-green\">60</span> yards.</p><p><span class=\"d3-color-gold\">Passive:</span> Summons a pair of ferret companions that each attack for <span class=\"d3-color-green\">100%</span> of your weapon damage as Physical.</p><p>The ferrets collect gold for you, increase gold found on monsters by <span class=\"d3-color-green\">10%</span>, and increase your movement speed by <span class=\"d3-color-green\">10%</span>.</p>",
      "simpleDescription" : "<p><span class=\"d3-color-gold\">Active:</span> Instantly pick up all nearby health globes and gold.</p><p><span class=\"d3-color-gold\">Passive:</span> Summons a pair of ferret companions that collect gold for you, increase the gold each monster drops, and increase your movement speed.</p>"
    }, {
      "requiredLevel" : 59,
      "name" : "Wolf Companion",
      "tooltipParams" : "rune/companion/c",
      "type" : "c",
      "description" : "<p><span class=\"d3-color-gold\">Active:</span> Your wolf howls, granting you and your allies within <span class=\"d3-color-green\">60</span> yards <span class=\"d3-color-green\">30%</span> increased damage for <span class=\"d3-color-green\">10</span> seconds.</p><p><span class=\"d3-color-gold\">Passive:</span> Summons a wolf companion that attacks enemies in front of him for <span class=\"d3-color-green\">100%</span> of your weapon damage as Physical.</p>",
      "simpleDescription" : "<p><span class=\"d3-color-gold\">Active:</span> Your wolf howls, granting you and your allies increased damage for a short duration.</p><p><span class=\"d3-color-gold\">Passive:</span> Summons a wolf companion that fights alongside you.</p>"
    } ],
    "primary" : false,
    "description" : "<p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">30</span> seconds</p><p><span class=\"d3-color-gold\">Active:</span> Your raven deals an additional <span class=\"d3-color-green\">500%</span> damage on its next attack.</p><p><span class=\"d3-color-gold\">Passive:</span> Summons a raven companion that pecks at enemies for <span class=\"d3-color-green\">100%</span> of your weapon damage as Physical.</p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">30</span> seconds</p><p><span class=\"d3-color-gold\">Active:</span> Your raven deals additional damage on its next attack.</p><p><span class=\"d3-color-gold\">Passive:</span> Summons a raven companion from the shadows.</p>"
  }, {
    "requiredLevel" : 19,
    "orderIndex" : 16,
    "tooltipParams" : "skill/demon-hunter/strafe",
    "categoryName" : "Archery",
    "categorySlug" : "archery",
    "icon" : "demonhunter_strafe",
    "name" : "Strafe",
    "slug" : "strafe",
    "runes" : [ {
      "requiredLevel" : 24,
      "name" : "Icy Trail",
      "tooltipParams" : "rune/strafe/b",
      "type" : "b",
      "description" : "<p>Leave an icy trail in your wake that deals <span class=\"d3-color-green\">300%</span> weapon damage as Cold over <span class=\"d3-color-green\">3</span> seconds and <span class=\"d3-color-green\">Chills</span> enemies for <span class=\"d3-color-green\">3</span> seconds.</p>",
      "simpleDescription" : "<p>Leave an icy trail as you move.</p>"
    }, {
      "requiredLevel" : 29,
      "name" : "Drifting Shadow",
      "tooltipParams" : "rune/strafe/d",
      "type" : "d",
      "description" : "<p>Movement speed increased to <span class=\"d3-color-green\">100%</span> of normal running speed while strafing.</p><p>Strafe&#39;s damage turns into Lightning.</p>",
      "simpleDescription" : "<p>Increase your movement speed when using Strafe.</p>"
    }, {
      "requiredLevel" : 37,
      "name" : "Stinging Steel",
      "tooltipParams" : "rune/strafe/e",
      "type" : "e",
      "description" : "<p>Throw out knives rather than arrows that deal an extra <span class=\"d3-color-green\">140%</span> damage on Critical Hits.</p>",
      "simpleDescription" : "<p>Throw out knives that deal additional damage on Critical Hits.</p>"
    }, {
      "requiredLevel" : 50,
      "name" : "Rocket Storm",
      "tooltipParams" : "rune/strafe/c",
      "type" : "c",
      "description" : "<p>In addition to regular shots, shoot off homing rockets for <span class=\"d3-color-green\">130%</span> weapon damage as Fire.</p>",
      "simpleDescription" : "<p>Shoot homing rockets while moving.</p>"
    }, {
      "requiredLevel" : 56,
      "name" : "Demolition",
      "tooltipParams" : "rune/strafe/a",
      "type" : "a",
      "description" : "<p>Throw out bouncy grenades that explode for <span class=\"d3-color-green\">460%</span> weapon damage as Fire to enemies within <span class=\"d3-color-green\">9</span> yards.</p>",
      "simpleDescription" : "<p>Throw grenades that randomly target enemies.</p>"
    } ],
    "primary" : true,
    "description" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">12</span> Hatred</p><p>Shoot at random nearby enemies for <span class=\"d3-color-green\">675%</span> weapon damage while moving at <span class=\"d3-color-green\">75%</span> of normal movement speed.</p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">12</span> Hatred</p><p>Shoot at nearby enemies while moving.</p>"
  }, {
    "requiredLevel" : 20,
    "orderIndex" : 17,
    "tooltipParams" : "skill/demon-hunter/elemental-arrow",
    "categoryName" : "Secondary",
    "categorySlug" : "secondary",
    "icon" : "demonhunter_elementalarrow",
    "name" : "Elemental Arrow",
    "slug" : "elemental-arrow",
    "runes" : [ {
      "requiredLevel" : 24,
      "name" : "Ball Lightning",
      "tooltipParams" : "rune/elemental-arrow/b",
      "type" : "b",
      "description" : "<p>Shoot a ball of lightning that electrocutes enemies along its path for <span class=\"d3-color-green\">300%</span> weapon damage as Lightning.</p>",
      "simpleDescription" : "<p>Shoot a ball of lightning that electrocutes enemies along its path.</p>"
    }, {
      "requiredLevel" : 29,
      "name" : "Frost Arrow",
      "tooltipParams" : "rune/elemental-arrow/a",
      "type" : "a",
      "description" : "<p>Shoot a frost arrow that hits an enemy for <span class=\"d3-color-green\">330%</span> weapon damage as Cold then splits into up to <span class=\"d3-color-green\">10</span> additional frost arrows. Enemies hit are <span class=\"d3-color-green\">Chilled</span> by <span class=\"d3-color-green\">60%</span> for <span class=\"d3-color-green\">1</span> seconds.</p>",
      "simpleDescription" : "<p>Shoot a frost arrow that splits into multiple arrows after hitting an enemy.</p>"
    }, {
      "requiredLevel" : 36,
      "name" : "Immolation Arrow",
      "tooltipParams" : "rune/elemental-arrow/c",
      "type" : "c",
      "description" : "<p>Shoot a fiery arrow that hits an enemy for <span class=\"d3-color-green\">300%</span> weapon damage as Fire and explodes, immolating the ground for <span class=\"d3-color-green\">315%</span> weapon damage as Fire over <span class=\"d3-color-green\">2</span> seconds to enemies within <span class=\"d3-color-green\">10</span> yards.</p>",
      "simpleDescription" : "<p>Shoot a fiery arrow that explodes.</p>"
    }, {
      "requiredLevel" : 43,
      "name" : "Lightning Bolts",
      "tooltipParams" : "rune/elemental-arrow/e",
      "type" : "e",
      "description" : "<p>Shoot an electrified bolt for <span class=\"d3-color-green\">300%</span> weapon damage as Lightning that Stuns enemies for <span class=\"d3-color-green\">1</span> second on a Critical Hit.</p>",
      "simpleDescription" : "<p>Shoot an electrified bolt that Stuns enemies on a Critical Hit.</p>"
    }, {
      "requiredLevel" : 59,
      "name" : "Nether Tentacles",
      "tooltipParams" : "rune/elemental-arrow/d",
      "type" : "d",
      "description" : "<p>Shoot a shadow tentacle that deals <span class=\"d3-color-green\">300%</span> weapon damage as Physical to enemies along its path and returns <span class=\"d3-color-green\">0.4%</span> of your maximum Life for each enemy hit.</p>",
      "simpleDescription" : "<p>Unleash shadow tentacles that return Life to you.</p>"
    } ],
    "primary" : true,
    "description" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">10</span> Hatred</p><p>Shoot a fire arrow that deals <span class=\"d3-color-green\">300%</span> weapon damage as Fire to all enemies it passes through.</p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">10</span> Hatred</p><p>Unleash a fiery arrow that pierces through enemies.</p>"
  }, {
    "requiredLevel" : 21,
    "orderIndex" : 18,
    "tooltipParams" : "skill/demon-hunter/marked-for-death",
    "categoryName" : "Hunting",
    "categorySlug" : "hunting",
    "icon" : "demonhunter_markedfordeath",
    "name" : "Marked for Death",
    "slug" : "marked-for-death",
    "runes" : [ {
      "requiredLevel" : 27,
      "name" : "Contagion",
      "tooltipParams" : "rune/marked-for-death/b",
      "type" : "b",
      "description" : "<p>When the enemy is killed, the mark spreads to the closest <span class=\"d3-color-green\">3</span> enemies within <span class=\"d3-color-green\">30</span> yards. This effect can chain repeatedly.</p>",
      "simpleDescription" : "<p>When the enemy is killed, additional enemies are Marked for Death.</p>"
    }, {
      "requiredLevel" : 31,
      "name" : "Valley of Death",
      "tooltipParams" : "rune/marked-for-death/c",
      "type" : "c",
      "description" : "<p>Mark an area on the ground of <span class=\"d3-color-green\">15</span> yard radius for <span class=\"d3-color-green\">15</span> seconds. Enemies in the area take <span class=\"d3-color-green\">15%</span> additional damage.</p>",
      "simpleDescription" : "<p>Mark an area on the ground. All enemies in the targeted area become Marked for Death.</p>"
    }, {
      "requiredLevel" : 39,
      "name" : "Grim Reaper",
      "tooltipParams" : "rune/marked-for-death/a",
      "type" : "a",
      "description" : "<p><span class=\"d3-color-green\">20%</span> of damage dealt to the marked enemy is also divided evenly among all enemies within <span class=\"d3-color-green\">20</span> yards.</p>",
      "simpleDescription" : "<p>A portion of damage dealt against the marked enemy is also applied to nearby enemies.</p>"
    }, {
      "requiredLevel" : 48,
      "name" : "Mortal Enemy",
      "tooltipParams" : "rune/marked-for-death/d",
      "type" : "d",
      "description" : "<p>Attacks you make against the marked enemy generate <span class=\"d3-color-green\">4</span> Hatred.</p>",
      "simpleDescription" : "<p>Attacks you make against the marked enemy generate Hatred.</p>"
    }, {
      "requiredLevel" : 60,
      "name" : "Death Toll",
      "tooltipParams" : "rune/marked-for-death/e",
      "type" : "e",
      "description" : "<p>Attackers heal for up to <span class=\"d3-color-green\">3%</span> of their maximum Life when damaging the marked enemy.</p>",
      "simpleDescription" : "<p>Damaging the marked enemy heals the attacker.</p>"
    } ],
    "primary" : true,
    "description" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">3</span> Discipline</p><p>Mark an enemy. The marked enemy takes <span class=\"d3-color-green\">20%</span> additional damage for the next <span class=\"d3-color-green\">30</span> seconds.</p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">3</span> Discipline</p><p>Mark an enemy to take additional damage from attacks.</p>"
  }, {
    "requiredLevel" : 22,
    "orderIndex" : 19,
    "tooltipParams" : "skill/demon-hunter/multishot",
    "categoryName" : "Archery",
    "categorySlug" : "archery",
    "icon" : "demonhunter_multishot",
    "name" : "Multishot",
    "slug" : "multishot",
    "runes" : [ {
      "requiredLevel" : 26,
      "name" : "Fire at Will",
      "tooltipParams" : "rune/multishot/d",
      "type" : "d",
      "description" : "<p>Reduce the Hatred cost to <span class=\"d3-color-green\">18</span>.</p><p>Multishot&#39;s damage turns into Lightning.</p>",
      "simpleDescription" : "<p>Reduce the Hatred cost and convert damage to Lightning.</p>"
    }, {
      "requiredLevel" : 31,
      "name" : "Burst Fire",
      "tooltipParams" : "rune/multishot/b",
      "type" : "b",
      "description" : "<p>Each time you fire, generate a burst of cold that damages nearby enemies within <span class=\"d3-color-green\">15</span> yards for <span class=\"d3-color-green\">200%</span> weapon damage as Cold.</p>",
      "simpleDescription" : "<p>Each time you fire, generate a burst of cold that damages nearby enemies.</p>"
    }, {
      "requiredLevel" : 39,
      "name" : "Suppression Fire",
      "tooltipParams" : "rune/multishot/e",
      "type" : "e",
      "description" : "<p>Knockback the first <span class=\"d3-color-green\">2</span> enemies hit.</p>",
      "simpleDescription" : "<p>Knockback some enemies hit.</p>"
    }, {
      "requiredLevel" : 46,
      "name" : "Full Broadside",
      "tooltipParams" : "rune/multishot/a",
      "type" : "a",
      "description" : "<p>Increase the damage of Multishot to <span class=\"d3-color-green\">460%</span> weapon damage.</p>",
      "simpleDescription" : "<p>Increase the damage of Multishot.</p>"
    }, {
      "requiredLevel" : 55,
      "name" : "Arsenal",
      "tooltipParams" : "rune/multishot/c",
      "type" : "c",
      "description" : "<p>Every time you fire, launch <span class=\"d3-color-green\">3</span> rockets at nearby enemies that each deal <span class=\"d3-color-green\">300%</span> weapon damage as Fire.</p>",
      "simpleDescription" : "<p>Every time you fire, launch multiple homing rockets.</p>"
    } ],
    "primary" : true,
    "description" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">25</span> Hatred</p><p>Fire a massive volley of arrows dealing <span class=\"d3-color-green\">360%</span> weapon damage to all enemies in the area.</p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">25</span> Hatred</p><p>Fire a massive volley of arrows in an arc.</p>"
  }, {
    "requiredLevel" : 25,
    "orderIndex" : 20,
    "tooltipParams" : "skill/demon-hunter/sentry",
    "categoryName" : "Devices",
    "categorySlug" : "devices",
    "icon" : "demonhunter_sentry",
    "name" : "Sentry",
    "slug" : "sentry",
    "runes" : [ {
      "requiredLevel" : 28,
      "name" : "Spitfire Turret",
      "tooltipParams" : "rune/sentry/c",
      "type" : "c",
      "description" : "<p>The turret will also fire homing rockets at random nearby enemies for <span class=\"d3-color-green\">120%</span> weapon damage as Fire.</p>",
      "simpleDescription" : "<p>The turret fires homing rockets at random enemies.</p>"
    }, {
      "requiredLevel" : 36,
      "name" : "Impaling Bolt",
      "tooltipParams" : "rune/sentry/b",
      "type" : "b",
      "description" : "<p>The turret now fires a bolt with a <span class=\"d3-color-green\">100%</span> chance to pierce.</p>",
      "simpleDescription" : "<p>The turret now fires a piercing bolt.</p>"
    }, {
      "requiredLevel" : 45,
      "name" : "Chain of Torment",
      "tooltipParams" : "rune/sentry/a",
      "type" : "a",
      "description" : "<p>Create a chain between you and the Sentry and between each Sentry that deals <span class=\"d3-color-green\">300%</span> weapon damage every second to each enemy it touches.</p>",
      "simpleDescription" : "<p>Create a chain between you and the Sentry and between each Sentry that damages enemies that touch the chain.</p>"
    }, {
      "requiredLevel" : 52,
      "name" : "Polar Station",
      "tooltipParams" : "rune/sentry/d",
      "type" : "d",
      "description" : "<p>The turret <span class=\"d3-color-green\">Chills</span> all nearby enemies within <span class=\"d3-color-green\">16</span> yards, Slowing their movement speed by <span class=\"d3-color-green\">60%</span>.</p>",
      "simpleDescription" : "<p>The turret <span class=\"d3-color-green\">Chills</span> nearby enemies.</p>"
    }, {
      "requiredLevel" : 60,
      "name" : "Guardian Turret",
      "tooltipParams" : "rune/sentry/e",
      "type" : "e",
      "description" : "<p>The turret also creates a shield that reduces damage taken by allies by <span class=\"d3-color-green\">15%</span>.</p>",
      "simpleDescription" : "<p>The turret creates a shield that reduces damage taken by allies.</p>"
    } ],
    "primary" : true,
    "description" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">20</span> Hatred</p><p>Summon a turret that fires at nearby enemies for <span class=\"d3-color-green\">280%</span> weapon damage. Lasts <span class=\"d3-color-green\">30</span> seconds.</p><p>You may have <span class=\"d3-color-green\">2</span> turrets active at a time.</p><p><span class=\"d3-color-yellow\">You gain a charge every <span class=\"d3-color-green\">8</span> seconds and can have up to <span class=\"d3-color-green\">2</span> charges stored at a time.</span></p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">20</span> Hatred</p><p>Summon a turret that automatically attacks nearby enemies.</p><p><span class=\"d3-color-yellow\">You gain a charge every <span class=\"d3-color-green\">8</span> seconds and can have up to <span class=\"d3-color-green\">2</span> charges stored at a time.</span></p>"
  }, {
    "requiredLevel" : 27,
    "orderIndex" : 21,
    "tooltipParams" : "skill/demon-hunter/cluster-arrow",
    "categoryName" : "Archery",
    "categorySlug" : "archery",
    "icon" : "demonhunter_clusterarrow",
    "name" : "Cluster Arrow",
    "slug" : "cluster-arrow",
    "runes" : [ {
      "requiredLevel" : 33,
      "name" : "Dazzling Arrow",
      "tooltipParams" : "rune/cluster-arrow/e",
      "type" : "e",
      "description" : "<p>Enemies hit by the grenades have a <span class=\"d3-color-green\">100%</span> chance to be stunned for <span class=\"d3-color-green\">1.5</span> seconds.</p><p>Cluster Arrow&#39;s damage turns into Lightning.</p>",
      "simpleDescription" : "<p>The grenades have a chance to Stun enemies.</p>"
    }, {
      "requiredLevel" : 36,
      "name" : "Shooting Stars",
      "tooltipParams" : "rune/cluster-arrow/b",
      "type" : "b",
      "description" : "<p>Instead of releasing grenades, release up to <span class=\"d3-color-green\">3</span> rockets at nearby enemies that each deal <span class=\"d3-color-green\">600%</span> weapon damage as Physical.</p>",
      "simpleDescription" : "<p>Release homing rockets instead of cluster grenades.</p>"
    }, {
      "requiredLevel" : 41,
      "name" : "Maelstrom",
      "tooltipParams" : "rune/cluster-arrow/d",
      "type" : "d",
      "description" : "<p>Instead of releasing grenades, release up to <span class=\"d3-color-green\">5</span> rockets at nearby enemies that each deal <span class=\"d3-color-green\">450%</span> weapon damage as Cold. You gain <span class=\"d3-color-green\">1%</span> Life per enemy hit.</p>",
      "simpleDescription" : "<p>Release rockets that replenish your Life on impact.</p>"
    }, {
      "requiredLevel" : 49,
      "name" : "Cluster Bombs",
      "tooltipParams" : "rune/cluster-arrow/c",
      "type" : "c",
      "description" : "<p>Launch a cluster through the air, dropping grenades in a straight line that each explode for <span class=\"d3-color-green\">525%</span> weapon damage as Fire.</p>",
      "simpleDescription" : "<p>Arc the arrow and drop multiple grenades along its path.</p>"
    }, {
      "requiredLevel" : 58,
      "name" : "Loaded for Bear",
      "tooltipParams" : "rune/cluster-arrow/a",
      "type" : "a",
      "description" : "<p>Increase the damage of the explosion at the impact location to <span class=\"d3-color-green\">770%</span> weapon damage as Fire.</p>",
      "simpleDescription" : "<p>Increase the damage at the impact point.</p>"
    } ],
    "primary" : true,
    "description" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">40</span> Hatred</p><p>Fire a cluster arrow that explodes for <span class=\"d3-color-green\">550%</span> weapon damage as Fire into a series of <span class=\"d3-color-green\">4</span> additional grenades that each explode for <span class=\"d3-color-green\">220%</span> weapon damage as Fire.</p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">40</span> Hatred</p><p>Fire a cluster arrow that fragments into grenades on impact.</p>"
  }, {
    "requiredLevel" : 30,
    "orderIndex" : 22,
    "tooltipParams" : "skill/demon-hunter/rain-of-vengeance",
    "categoryName" : "Archery",
    "categorySlug" : "archery",
    "icon" : "demonhunter_rainofvengeance",
    "name" : "Rain of Vengeance",
    "slug" : "rain-of-vengeance",
    "runes" : [ {
      "requiredLevel" : 35,
      "name" : "Dark Cloud",
      "tooltipParams" : "rune/rain-of-vengeance/b",
      "type" : "b",
      "description" : "<p>Launch a volley of guided arrows that rain down on enemies for <span class=\"d3-color-green\">3500%</span> weapon damage over <span class=\"d3-color-green\">8</span> seconds.</p>",
      "simpleDescription" : "<p>Launch a volley of guided arrows that rain down on enemies.</p>"
    }, {
      "requiredLevel" : 40,
      "name" : "Shade",
      "tooltipParams" : "rune/rain-of-vengeance/a",
      "type" : "a",
      "description" : "<p>Fire a massive volley of arrows at a large area. Arrows fall from the sky dealing <span class=\"d3-color-green\">2800%</span> weapon damage as Lightning over <span class=\"d3-color-green\">5</span> seconds to all enemies in the area.</p>",
      "simpleDescription" : "<p>Unleash a powerful torrent of arrows from the sky.</p>"
    }, {
      "requiredLevel" : 47,
      "name" : "Stampede",
      "tooltipParams" : "rune/rain-of-vengeance/e",
      "type" : "e",
      "description" : "<p>Summon a wave of <span class=\"d3-color-green\">10</span> Shadow Beasts to tear across the ground, knocking back enemies and dealing <span class=\"d3-color-green\">4600%</span> total weapon damage as Fire over <span class=\"d3-color-green\">3</span> seconds.</p>",
      "simpleDescription" : "<p>Summon Shadow Beasts that swoop along the ground and damage enemies they hit.</p>"
    }, {
      "requiredLevel" : 54,
      "name" : "Anathema",
      "tooltipParams" : "rune/rain-of-vengeance/c",
      "type" : "c",
      "description" : "<p>Summon a Shadow Beast that drops grenades from the sky dealing <span class=\"d3-color-green\">5800%</span> weapon damage as Fire over <span class=\"d3-color-green\">2</span> seconds.</p>",
      "simpleDescription" : "<p>Summon a single Shadow Beast that hovers overhead and drops grenades.</p>"
    }, {
      "requiredLevel" : 60,
      "name" : "Flying Strike",
      "tooltipParams" : "rune/rain-of-vengeance/d",
      "type" : "d",
      "description" : "<p>Call a group of <span class=\"d3-color-green\">8</span> Shadow Beasts to plummet from the sky at a targeted location dealing <span class=\"d3-color-green\">3800%</span> total weapon damage as Cold over <span class=\"d3-color-green\">4</span> seconds and <span class=\"d3-color-green\">Freezing</span> enemies hit for <span class=\"d3-color-green\">2</span> seconds.</p>",
      "simpleDescription" : "<p>Call Shadow Beasts to plummet from the sky and bomb the target location, Freezing enemies in the area.</p>"
    } ],
    "primary" : true,
    "description" : "<p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">30</span> seconds</p><p>Fire a massive volley of arrows at a large area. Arrows fall from the sky dealing <span class=\"d3-color-green\">1500%</span> weapon damage over <span class=\"d3-color-green\">5</span> seconds to all enemies in the area.</p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">30</span> seconds</p><p>Unleash a torrent of arrows from the sky.</p>"
  }, {
    "requiredLevel" : 61,
    "orderIndex" : 23,
    "tooltipParams" : "skill/demon-hunter/vengeance",
    "categoryName" : "Devices",
    "categorySlug" : "devices",
    "icon" : "x1_demonhunter_vengeance",
    "name" : "Vengeance",
    "slug" : "vengeance",
    "runes" : [ {
      "requiredLevel" : 62,
      "name" : "Personal Mortar",
      "tooltipParams" : "rune/vengeance/c",
      "type" : "c",
      "description" : "<p>Instead of Homing Rockets, launch <span class=\"d3-color-green\">2</span> Grenades at random enemies outside melee range on every attack that explode for <span class=\"d3-color-green\">150%</span> weapon damage each as Fire.</p>",
      "simpleDescription" : "<p>Instead of firing homing rockets, lob grenades at nearby enemies.</p>"
    }, {
      "requiredLevel" : 63,
      "name" : "Dark Heart",
      "tooltipParams" : "rune/vengeance/b",
      "type" : "b",
      "description" : "<p>Vengeance pours out of you, continuously dealing <span class=\"d3-color-green\">325%</span> weapon damage as Lightning per second to enemies around you.</p>",
      "simpleDescription" : "<p>Vengeance pours out of you, continuously damaging nearby enemies.</p>"
    }, {
      "requiredLevel" : 65,
      "name" : "Side Cannons",
      "tooltipParams" : "rune/vengeance/d",
      "type" : "d",
      "description" : "<p>Instead of Homing Rockets, the side guns are powered up into slower-firing cannons that deal <span class=\"d3-color-green\">225%</span> weapon damage and heal you for <span class=\"d3-color-green\">3.0%</span> of maximum Life per enemy hit.</p>",
      "simpleDescription" : "<p>Instead of Homing Rockets, the side guns are powered up into cannons that deal increased damage and heal you.</p>"
    }, {
      "requiredLevel" : 67,
      "name" : "Seethe",
      "tooltipParams" : "rune/vengeance/e",
      "type" : "e",
      "description" : "<p>Gain <span class=\"d3-color-green\">10</span> Hatred per second.</p>",
      "simpleDescription" : "<p>Increase Hatred regeneration.</p>"
    }, {
      "requiredLevel" : 69,
      "name" : "From the Shadows",
      "tooltipParams" : "rune/vengeance/a",
      "type" : "a",
      "description" : "<p>Instead of Homing Rockets, summon allies from the shadows that attack for <span class=\"d3-color-green\">120%</span> weapon damage as Cold and <span class=\"d3-color-green\">Freeze</span> your enemies for <span class=\"d3-color-green\">2</span> seconds.</p>",
      "simpleDescription" : "<p>Instead of Homing Rockets, summon allies from the shadows that attack and <span class=\"d3-color-green\">Freeze</span> your enemies.</p>"
    } ],
    "primary" : false,
    "description" : "<p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">90</span> seconds</p><p>Turn into the physical embodiment of Vengeance for <span class=\"d3-color-green\">15</span> seconds.</p><p><span class=\"tooltip-icon-bullet\"></span> <span class=\"d3-color-gold\">Side Guns:</span> Gain <span class=\"d3-color-green\">4</span> additional piercing shots for <span class=\"d3-color-green\">60%</span> weapon damage each on every attack.<br/><span class=\"tooltip-icon-bullet\"></span> <span class=\"d3-color-gold\">Homing Rockets:</span> Shoot <span class=\"d3-color-green\">4</span> rockets at nearby enemies for <span class=\"d3-color-green\">40%</span> weapon damage each on every attack.</p>",
    "simpleDescription" : "<p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">90</span> seconds</p><p>Turn into the physical embodiment of Vengeance for <span class=\"d3-color-green\">15</span> seconds.</p>"
  } ],
  "traits" : [ {
    "requiredLevel" : 10,
    "orderIndex" : 0,
    "tooltipParams" : "skill/demon-hunter/thrill-of-the-hunt",
    "icon" : "demonhunter_passive_thrillofthehunt",
    "name" : "Thrill of the Hunt",
    "slug" : "thrill-of-the-hunt",
    "description" : "<p>Every <span class=\"d3-color-green\">6</span> seconds, your next skill that costs Hatred will immobilize all enemies hit for <span class=\"d3-color-green\">2</span> seconds.</p>",
    "simpleDescription" : "<p>Every <span class=\"d3-color-green\">6</span> seconds, your next skill that costs Hatred will immobilize all enemies hit for <span class=\"d3-color-green\">2</span> seconds.</p>"
  }, {
    "requiredLevel" : 10,
    "orderIndex" : 1,
    "tooltipParams" : "skill/demon-hunter/tactical-advantage",
    "icon" : "demonhunter_passive_tacticaladvantage",
    "name" : "Tactical Advantage",
    "slug" : "tactical-advantage",
    "description" : "<p>Whenever you use Vault, Smoke Screen, or backflip with Evasive Fire you gain <span class=\"d3-color-green\">60%</span> movement speed for <span class=\"d3-color-green\">2</span> seconds.</p>",
    "simpleDescription" : "<p>Whenever you use Vault, Smoke Screen, or backflip with Evasive Fire you gain <span class=\"d3-color-green\">60%</span> movement speed for <span class=\"d3-color-green\">2</span> seconds.</p>"
  }, {
    "requiredLevel" : 13,
    "orderIndex" : 2,
    "tooltipParams" : "skill/demon-hunter/blood-vengeance",
    "icon" : "demonhunter_passive_vengeance",
    "name" : "Blood Vengeance",
    "slug" : "blood-vengeance",
    "description" : "<p>Your maximum Hatred is increased by <span class=\"d3-color-green\">25</span>. In addition, gain <span class=\"d3-color-green\">30</span> Hatred and <span class=\"d3-color-green\">3</span> Discipline when you are healed by a health globe.</p>",
    "simpleDescription" : "<p>Your maximum Hatred is increased by <span class=\"d3-color-green\">25</span>. In addition, gain <span class=\"d3-color-green\">30</span> Hatred and <span class=\"d3-color-green\">3</span> Discipline when you are healed by a health globe.</p>"
  }, {
    "requiredLevel" : 16,
    "orderIndex" : 3,
    "tooltipParams" : "skill/demon-hunter/steady-aim",
    "icon" : "demonhunter_passive_steadyaim",
    "name" : "Steady Aim",
    "slug" : "steady-aim",
    "description" : "<p>As long as there are no enemies within <span class=\"d3-color-green\">10</span> yards, all damage is increased by <span class=\"d3-color-green\">20%</span>.</p>",
    "simpleDescription" : "<p>As long as there are no enemies within <span class=\"d3-color-green\">10</span> yards, all damage is increased by <span class=\"d3-color-green\">20%</span>.</p>"
  }, {
    "requiredLevel" : 20,
    "orderIndex" : 4,
    "tooltipParams" : "skill/demon-hunter/cull-the-weak",
    "icon" : "demonhunter_passive_culltheweak",
    "name" : "Cull the Weak",
    "slug" : "cull-the-weak",
    "description" : "<p>Increase damage against Slowed or Chilled enemies by <span class=\"d3-color-green\">20%</span>.</p>",
    "simpleDescription" : "<p>Increase damage against Slowed or Chilled enemies by <span class=\"d3-color-green\">20%</span>.</p>"
  }, {
    "requiredLevel" : 20,
    "orderIndex" : 5,
    "tooltipParams" : "skill/demon-hunter/night-stalker",
    "icon" : "demonhunter_passive_nightstalker",
    "name" : "Night Stalker",
    "slug" : "night-stalker",
    "description" : "<p>Your primary skills generate an additional <span class=\"d3-color-green\">4</span> Hatred.</p>",
    "simpleDescription" : "<p>Your primary skills generate an additional <span class=\"d3-color-green\">4</span> Hatred.</p>"
  }, {
    "requiredLevel" : 25,
    "orderIndex" : 6,
    "tooltipParams" : "skill/demon-hunter/brooding",
    "icon" : "demonhunter_passive_brooding",
    "name" : "Brooding",
    "slug" : "brooding",
    "description" : "<p>Gain <span class=\"d3-color-green\">3.0%</span> Life regeneration per second for every second you remain stationary, stacking up to <span class=\"d3-color-green\">3</span> times. This bonus is reset <span class=\"d3-color-green\">5</span> seconds after you move.</p>",
    "simpleDescription" : "<p>Gain <span class=\"d3-color-green\">3.0%</span> Life regeneration per second for every second you remain stationary, stacking up to <span class=\"d3-color-green\">3</span> times. This bonus is reset <span class=\"d3-color-green\">5</span> seconds after you move.</p>"
  }, {
    "requiredLevel" : 27,
    "orderIndex" : 7,
    "tooltipParams" : "skill/demon-hunter/hot-pursuit",
    "icon" : "demonhunter_passive_hotpursuit",
    "name" : "Hot Pursuit",
    "slug" : "hot-pursuit",
    "description" : "<p>Increase movement speed by <span class=\"d3-color-green\">20%</span> for <span class=\"d3-color-green\">2</span> seconds when you hit an enemy.</p>",
    "simpleDescription" : "<p>Increase movement speed by <span class=\"d3-color-green\">20%</span> for <span class=\"d3-color-green\">2</span> seconds when you hit an enemy.</p>"
  }, {
    "requiredLevel" : 30,
    "orderIndex" : 8,
    "tooltipParams" : "skill/demon-hunter/archery",
    "icon" : "demonhunter_passive_archery",
    "name" : "Archery",
    "slug" : "archery",
    "description" : "<p>Gain a bonus based on your weapon type:<br/>Bow: <span class=\"d3-color-green\">8%</span> increased damage<br/>Crossbow: <span class=\"d3-color-green\">50%</span> Critical Hit Damage<br/>Hand Crossbow: <span class=\"d3-color-green\">5%</span> Critical Hit Chance<br/>2nd Hand Crossbow: <span class=\"d3-color-green\">1</span> Hatred per Second</p>",
    "simpleDescription" : "<p>Gain a bonus based on your weapon type:<br/>Bow: <span class=\"d3-color-green\">8%</span> increased damage<br/>Crossbow: <span class=\"d3-color-green\">50%</span> Critical Hit Damage<br/>Hand Crossbow: <span class=\"d3-color-green\">5%</span> Critical Hit Chance<br/>2nd Hand Crossbow: <span class=\"d3-color-green\">1</span> Hatred per Second</p>"
  }, {
    "requiredLevel" : 30,
    "orderIndex" : 9,
    "tooltipParams" : "skill/demon-hunter/numbing-traps",
    "icon" : "demonhunter_passive_numbingtraps",
    "name" : "Numbing Traps",
    "slug" : "numbing-traps",
    "description" : "<p>Enemies you Slow or hit with Fan of Knives, Spike Trap, Caltrops, Grenades, and Sentry fire have their damage reduced by <span class=\"d3-color-green\">25%</span> for <span class=\"d3-color-green\">3</span> seconds.</p>",
    "simpleDescription" : "<p>Enemies you Slow or hit with Fan of Knives, Spike Trap, Caltrops, Grenades, and Sentry fire have their damage reduced by <span class=\"d3-color-green\">25%</span> for <span class=\"d3-color-green\">3</span> seconds.</p>"
  }, {
    "requiredLevel" : 35,
    "orderIndex" : 10,
    "tooltipParams" : "skill/demon-hunter/perfectionist",
    "icon" : "demonhunter_passive_perfectionist",
    "name" : "Perfectionist",
    "slug" : "perfectionist",
    "description" : "<p>Reduce the Discipline cost of all skills by <span class=\"d3-color-green\">10%</span>. Increase your Armor and resistance to all damage types by <span class=\"d3-color-green\">10%</span>.</p><p>Discipline is used to fuel many of your tactical and defensive skills.</p>",
    "simpleDescription" : "<p>Reduce the Discipline cost of all skills by <span class=\"d3-color-green\">10%</span>. Increase your Armor and resistance to all damage types by <span class=\"d3-color-green\">10%</span>.</p><p>Discipline is used to fuel many of your tactical and defensive skills.</p>"
  }, {
    "requiredLevel" : 40,
    "orderIndex" : 11,
    "tooltipParams" : "skill/demon-hunter/custom-engineering",
    "icon" : "demonhunter_passive_customengineering",
    "name" : "Custom Engineering",
    "slug" : "custom-engineering",
    "description" : "<p>Increase the duration of your Caltrops, Marked for Death, Spike Trap, and Sentry by <span class=\"d3-color-green\">100%</span>.</p><p>Increase the maximum number and charges of Sentries to <span class=\"d3-color-green\">3</span> and number of Spike Traps to <span class=\"d3-color-green\">6</span>.</p>",
    "simpleDescription" : "<p>Increase the duration of your Caltrops, Marked for Death, Spike Trap, and Sentry by <span class=\"d3-color-green\">100%</span>.</p><p>Increase the maximum number and charges of Sentries to <span class=\"d3-color-green\">3</span> and number of Spike Traps to <span class=\"d3-color-green\">6</span>.</p>"
  }, {
    "requiredLevel" : 45,
    "orderIndex" : 12,
    "tooltipParams" : "skill/demon-hunter/grenadier",
    "icon" : "demonhunter_passive_grenadier",
    "name" : "Grenadier",
    "slug" : "grenadier",
    "description" : "<p>Increase the damage of grenades by <span class=\"d3-color-green\">10%</span>.<br/>Increase the explosion size of grenades by <span class=\"d3-color-green\">20%</span>.</p><p>Upon death, you drop a giant grenade that explodes for <span class=\"d3-color-green\">1000%</span> weapon damage as Fire.</p>",
    "simpleDescription" : "<p>Increase the damage of grenades by <span class=\"d3-color-green\">10%</span>.<br/>Increase the explosion size of grenades by <span class=\"d3-color-green\">20%</span>.</p><p>Upon death, you drop a giant grenade that explodes for <span class=\"d3-color-green\">1000%</span> weapon damage as Fire.</p>"
  }, {
    "requiredLevel" : 50,
    "orderIndex" : 13,
    "tooltipParams" : "skill/demon-hunter/sharpshooter",
    "icon" : "demonhunter_passive_sharpshooter",
    "name" : "Sharpshooter",
    "slug" : "sharpshooter",
    "description" : "<p>Gain <span class=\"d3-color-green\">4%</span> Critical Hit Chance every second. This bonus is reset <span class=\"d3-color-green\">1</span> seconds after you successfully critically hit.</p>",
    "simpleDescription" : "<p>Gain <span class=\"d3-color-green\">4%</span> Critical Hit Chance every second. This bonus is reset <span class=\"d3-color-green\">1</span> seconds after you successfully critically hit.</p>"
  }, {
    "requiredLevel" : 55,
    "orderIndex" : 14,
    "tooltipParams" : "skill/demon-hunter/ballistics",
    "icon" : "demonhunter_passive_ballistics",
    "name" : "Ballistics",
    "slug" : "ballistics",
    "description" : "<p>Increase damage of rockets by <span class=\"d3-color-green\">100%</span>.</p><p>In addition, you have a <span class=\"d3-color-green\">20%</span> chance to fire a homing rocket for <span class=\"d3-color-green\">150%</span> weapon damage when you attack.</p>",
    "simpleDescription" : "<p>Increase damage of rockets by <span class=\"d3-color-green\">100%</span>.</p><p>In addition, you have a <span class=\"d3-color-green\">20%</span> chance to fire a homing rocket for <span class=\"d3-color-green\">150%</span> weapon damage when you attack.</p>"
  }, {
    "requiredLevel" : 64,
    "orderIndex" : 15,
    "tooltipParams" : "skill/demon-hunter/ambush",
    "icon" : "x1_demonhunter_passive_ambush",
    "name" : "Ambush",
    "slug" : "ambush",
    "description" : "<p>You deal <span class=\"d3-color-green\">40%</span> additional damage to enemies above <span class=\"d3-color-green\">75%</span> health.</p>",
    "simpleDescription" : "<p>You deal <span class=\"d3-color-green\">40%</span> additional damage to enemies above <span class=\"d3-color-green\">75%</span> health.</p>"
  }, {
    "requiredLevel" : 66,
    "orderIndex" : 16,
    "tooltipParams" : "skill/demon-hunter/awareness",
    "icon" : "x1_demonhunter_passive_awareness",
    "name" : "Awareness",
    "slug" : "awareness",
    "description" : "<p>When you receive fatal damage, you instead vanish for <span class=\"d3-color-green\">2</span> seconds and regenerate <span class=\"d3-color-green\">50%</span> of maximum Life.</p><p>This effect may occur once every <span class=\"d3-color-green\">60</span> seconds.</p>",
    "simpleDescription" : "<p>When you receive fatal damage, you instead vanish for <span class=\"d3-color-green\">2</span> seconds and regenerate <span class=\"d3-color-green\">50%</span> of maximum Life.</p><p>This effect may occur once every <span class=\"d3-color-green\">60</span> seconds.</p>"
  }, {
    "requiredLevel" : 68,
    "orderIndex" : 17,
    "tooltipParams" : "skill/demon-hunter/single-out",
    "icon" : "x1_demonhunter_passive_singleout",
    "name" : "Single Out",
    "slug" : "single-out",
    "description" : "<p>Gain <span class=\"d3-color-green\">25%</span> Critical Hit Chance against enemies who are more than <span class=\"d3-color-green\">20</span> yards away from any other enemies.</p>",
    "simpleDescription" : "<p>Gain <span class=\"d3-color-green\">25%</span> Critical Hit Chance against enemies who are more than <span class=\"d3-color-green\">20</span> yards away from any other enemies.</p>"
  } ]
};
